### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by lukasbystricky** [hlund05/adam-smith_the-theory-of-moral-sentiments#1]
- [x] Add semantics around royalty names introduced in 6308880
- [x] We typically only do sound-alike modernizations, so I think the following commits should be reverted: e0c5f4f, f672ee4, 606b685, 23ec80a, 42302b8,
- [x] "worth while" (955d579) is a particular case that we don't modernize. If we do decide to modernize it later it would be at a corpus level.  
- [x] Starting a sentence after a question mark or an exclamation mark is also a common enough occurrence that we allow. Again if we do modernize this it would be done at a corpus level. This affects 1b6cbe0, a990285, ae3000f, 2e9466e, 2941f50
- [x] Remove "Chapter" from chapter titles (SEMoS [8.1.4](https://standardebooks.org/manual/1.8.0/single-page#8.1.4))
- [x] Several Sections (e.g. section-1-2, section-2-1, section-2-3, section-6-2, section-7-2, section-7-3) have introductions. These should be enclosed in their own `<section>` tags. They can stay in the same file as they're in now.
- [x] The `<cite>` tags in e3596de can be removed
- [x] Roman numerals should be in upper case, including those in the endnotes (the only exception I've seen is for page numbers)
- [x] Should endnote 3 be a blockquote? It looks like it could be.

**Comment by hlund05** [comment]
Hi Lukas, thanks again for the review/feedback.  These items have all been addressed.  Similar to the Sections that have introductions, Part VI also has a brief introduction, so I put this into a separate <section> tag as well.

**Comment by lukasbystricky** [comment]
Sorry I was a bit unclear (and incorrect) above. About the semantics around the royalty names, I meant add the missing inflections around the roman numerals. No need to add the semantics around the actual name. So be862d7 can be dropped.

I was wrong about the keeping the introductions in the same file as their parents. This ends up making the ToC look like the chapters are children of the introduction. If you move the introduction `<section>` to the file containing the first chapter then everything in the ToC looks like it should (after re-running build-toc).

**Comment by hlund05** [comment]
Got it, thanks for the clarifications.  These changes have been made, and yes the TOC builds correctly now.

**Comment by lukasbystricky** [comment]
Sorry again, what you have looks right but when if you run `se build-title` it changes the titles of some of the chapters. This was my fault again. I hadn't noticed that in the previous attempt you had the two sections sequentially. If you nest them instead (e.g. put section-1-2-introduction inside section-1-2) then the ToC looks as it should and the titles of the chapters don't change. The exception is part-6. Since part-6 doesn't have a data-parent you don't want to nest the introduction section. In other words you can place the introduction section directly after the part-6 section. 

It's all a bit confusing, but basically in the end you want the ToC to appear like it does now (the xhtml will change because you'll be moving the introductions back the parent files), but `se build-title` shouldn't change anything.

**Comment by hlund05** [comment]
Hi Lukas - I think it's good now, but let me know if you agree.  se build-title and build-toc are not making any changes to the files.

**Comment by lukasbystricky** [comment]
Ok, looks good to me. I'll pass it off to Alex.
